Added some details to custom menu documentation
sibiraj-s/ngx-editor pull request #308
Opened 2021-01-05 18:15 UTC by MateMahinKhan

This PR contains:

- [ ] bugfix
- [ ] feature
- [ ] refactor
- [ ] tests
- [x] documentation
- [ ] others

### Breaking Changes?

- [ ] yes
- [x] no

### Checklist

- [ ] commit messages follow the [Conventional Commits](https://conventionalcommits.org/) pattern
  - A feature commit message is prefixed "feat:"
  - A bugfix commit message is prefixed "fix:"
  - A document related commit is prefixed "docs:"
- [x] docs have been added / updated (for bug fixes / features)

### Describe Your Changes

Added some details for Custom Menu. There wasn't anything missing from the existing documentation but I've added some explicit details.

### Does this PR affects any existing issues?

- [ ] yes
- [x] no

2021-01-06 03:30 UTC, sibiraj-s requested changes
Thanks for the PR. left some suggestions.

2021-01-06 03:30 UTC, sibiraj-s commented on docs/menu.md
> +The editorView will be available from the init function. Create `customMenu` as a template variable using the custom-menu component.
```suggestion
Create `customMenu` as a template variable using the custom-menu component.
```

init function no longer exists. can you remove this line

2021-01-06 03:30 UTC, sibiraj-s commented on docs/menu.md
> +The editorView will be available from the init function. Create `customMenu` as a template variable using the custom-menu component.
> Create `customMenu` as a template variable using the custom-menu component.

this somehow feels like the editor is providing a custom menu component to create custom, but it is create a template and pass the ref as a input to the menu component, via `customMenuRef`

2021-01-06 03:30 UTC, sibiraj-s commented on docs/menu.md
> +Menu is not part of the editor component. Include `ngx-editor-menu` in your HTML manually. The custom-menu items will be added after the items on the toolbar.
```suggestion
Menu is not part of the editor component. Include `ngx-editor-menu` in your HTML manually. The custom-menu will be inserted after the toolbar items.
```

2021-01-06 03:30 UTC, sibiraj-s commented on docs/menu.md
> +Menu is not part of the editor component. Include `ngx-editor-menu` in your HTML manually. The custom-menu items will be added after the items on the toolbar.
and this line can be moved into the `CustomMenu` section. The info seems early.

2021-01-06 16:51 UTC, MateMahinKhan commented
Incorporated your suggestions. 

I changed the line to `Create 'customMenu' as a template variable using the newly created custom-menu component.` I'm not sure adding newly created might fix the confusion.

2021-01-07 04:04 UTC, sibiraj-s approved these changes
Thanks @MateMahinKhan.

2021-01-07 04:05 UTC, sibiraj-s commented
I made some changes to the custom menu part. I hope it is explanatory. 

Also, please follow the commit guidelines. I will squash merge this for now.

2021-01-07 04:05 UTC, merged