fix: export getDefaultPlugins and getKeyboardShortcuts methods
sibiraj-s/ngx-editor pull request #393
Opened 2022-04-12 22:24 UTC by paulirwin

In order to submit this PR, I had to add support for building on Windows too using `run-script-os`.

This PR contains:

- [X] bugfix
- [ ] feature
- [ ] refactor
- [ ] tests
- [ ] documentation
- [ ] others

### Breaking Changes?

- [ ] yes
- [X] no

### Checklist

- [X] commit messages follow the [Conventional Commits](https://conventionalcommits.org/) pattern
  - A feature commit message is prefixed "feat:"
  - A bugfix commit message is prefixed "fix:"
  - A document related commit is prefixed "docs:"
- [ ] docs have been added / updated (for bug fixes / features)

TODO: is a docs update needed here?

### Describe Your Changes

### Does this PR affects any existing issues?

- [X] yes
- [ ] no

Fixes #373

2022-04-13 01:11 UTC, sibiraj-s requested changes
Looks good. Suggestion to replace `run-script-os` with `is-ci`

2022-04-13 01:11 UTC, sibiraj-s commented on package.json
> +    "prepare": "run-script-os",
```bash
npm i -D is-ci
```

we can install `is-ci`, which is already part of the dependency tree 

```suggestion
    "prepare": "is-ci || husky install",
```
we don't need `run-script-os`

2022-04-13 14:40 UTC, paulirwin commented
@sibiraj-s PR updated with those changes.

2022-04-26 03:44 UTC, sibiraj-s approved these changes

2022-04-26 03:51 UTC, sibiraj-s commented
Sorry for the delay. had some personal emergencies.

2022-04-26 03:52 UTC, merged